apiVersion: batch/v1
kind: Job
metadata:
  name: megaboom
spec:
  activeDeadlineSeconds: 300 # 5 minutes
  parallelism: 100
  template:
    metadata:
      name: megaboom
    spec:
      containers:
        - name: megaboom
          image: quay.io/arschles/boom:0.1.0
          imagePullPolicy: IfNotPresent
          # 10,000 requests * 10 pods (parallelism) = 100,000 total requests
          # 100 concurrent requests * 100 pods = 1,000 max requests concurrently in flight
          command: ["boom", "-n", "10000", "-c", "100", "http://kubehttpbin.104.155.138.54.nip.io/get"]
      restartPolicy: Never
