apiVersion: batch/v1
kind: Job
metadata:
  name: megaboom
spec:
  activeDeadlineSeconds: 300 # 5 minutes
  parallelism: 10
  template:
    metadata:
      name: megaboom
    spec:
      containers:
        - name: megaboom
          image: quay.io/arschles/boom:0.1.0
          imagePullPolicy: IfNotPresent
          command: ["boom", "-n", "10000", "-c", "100", "http://kubehttpbin.org/get"]
      restartPolicy: Never
